# Generated by Django 2.2.6 on 2019-11-07 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191106_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='body',
            field=models.TextField(verbose_name='التعليق'),
        ),
        migrations.AlterField(
            model_name='command',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان التعليق'),
        ),
        migrations.AlterField(
            model_name='command',
            name='user_command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_command', to=settings.AUTH_USER_MODEL),
        ),
    ]
