# Generated by Django 2.2.6 on 2019-11-09 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191107_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='active',
            field=models.BooleanField(default=True, verbose_name='الفعالية'),
        ),
        migrations.AlterField(
            model_name='command',
            name='date_command',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعليق'),
        ),
        migrations.AlterField(
            model_name='command',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command', to='blog.Post', verbose_name='التدوينة'),
        ),
        migrations.AlterField(
            model_name='command',
            name='title',
            field=models.CharField(help_text='اجعل العنوان وصفاً لعموم للتعليق', max_length=50, verbose_name='عنوان التعليق'),
        ),
        migrations.AlterField(
            model_name='command',
            name='user_command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_command', to=settings.AUTH_USER_MODEL, verbose_name='المعلق'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='نص التدوينة'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='الحد الاقصى 100 خانة', max_length=100, verbose_name='عنوان التدوينة'),
        ),
    ]
