# Generated by Django 2.2.6 on 2019-11-09 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='img', upload_to='image')),
                ('phone_number', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('small_info', models.TextField(help_text='تفاصيل صغيرة عن نفسك', max_length=1000, verbose_name='تفاصيل صغيرة')),
                ('city', models.CharField(max_length=15, verbose_name='المدينة')),
                ('country', models.CharField(max_length=15, verbose_name='الدولة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
